<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="XSD">
      <schema location="../../SensorActionSensorAction_1.xsd"/>
      <rootElement name="actionData" namespace="http://xmlns.oracle.com/bpel/sensor"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../Training/POProcessing/Orders.wsdl"/>
      <rootElement name="_Orders1Collection" namespace="http://xmlns.oracle.com/bam"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.0.0(build 090618.1440.5219) AT [WED SEP 16 13:39:25 PDT 2009]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xpath20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:ns0="http://xmlns.oracle.com/bam"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:tns="http://xmlns.oracle.com/bpel/sensor"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:sensor="http://xmlns.oracle.com/ns/order"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:nxsd="http://xmlns.oracle.com/pcbpel/nxsd"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                exclude-result-prefixes="xsi xsl tns sensor nxsd xsd ns0 xsi xpath20 bpws mhdr oraext dvm hwf med ids xdk xref ora socket">
  <xsl:template match="/">
    <ns0:_Orders1Collection>
      <ns0:_Orders1>
        <ns0:_Order_ID>
          <xsl:value-of select="/tns:actionData/tns:payload/tns:variableData/tns:data/sensor:Order/sensor:orderId"/>
        </ns0:_Order_ID>
        <ns0:_Customer_ID>
          <xsl:value-of select="/tns:actionData/tns:payload/tns:variableData/tns:data/sensor:Order/sensor:customerId"/>
        </ns0:_Customer_ID>
        <ns0:_Product_Name>
          <xsl:value-of select="/tns:actionData/tns:payload/tns:variableData/tns:data/sensor:Order/sensor:prodName"/>
        </ns0:_Product_Name>
        <ns0:_Item_Type>
          <xsl:value-of select="/tns:actionData/tns:payload/tns:variableData/tns:data/sensor:Order/sensor:itemType"/>
        </ns0:_Item_Type>
        <ns0:_Price>
          <xsl:value-of select="/tns:actionData/tns:payload/tns:variableData/tns:data/sensor:Order/sensor:price"/>
        </ns0:_Price>
        <ns0:_Quantity>
          <xsl:value-of select="/tns:actionData/tns:payload/tns:variableData/tns:data/sensor:Order/sensor:qty"/>
        </ns0:_Quantity>
        <ns0:_Status>
          <xsl:value-of select="/tns:actionData/tns:payload/tns:variableData/tns:data/sensor:Order/sensor:status"/>
        </ns0:_Status>
      </ns0:_Orders1>
    </ns0:_Orders1Collection>
  </xsl:template>
</xsl:stylesheet>
