<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../approveLargeOrder.wsdl"/>
      <rootElement name="Order" namespace="http://xmlns.oracle.com/ns/order"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../WriteApprovalResults.wsdl"/>
      <rootElement name="Order" namespace="http://xmlns.oracle.com/ns/order"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.0.0(build 090618.1440.5219) AT [THU SEP 10 11:53:31 PDT 2009]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xpath20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:ns1="http://xmlns.oracle.com/ns/order"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/file/POProcessing/POProcessing/WriteApprovalResults%2F"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:client="http://xmlns.oracle.com/POProcessing/POProcessing/approveLargeOrder"
                exclude-result-prefixes="xsi xsl ns1 plnk xsd wsdl client tns xpath20 bpws mhdr oraext dvm hwf med ids xdk xref ora socket">
  <xsl:template match="/">
    <ns1:Order>
      <ns1:customerId>
        <xsl:value-of select="/ns1:Order/ns1:customerId"/>
      </ns1:customerId>
      <ns1:orderId>
        <xsl:value-of select="/ns1:Order/ns1:orderId"/>
      </ns1:orderId>
      <ns1:prodName>
        <xsl:value-of select="/ns1:Order/ns1:prodName"/>
      </ns1:prodName>
      <ns1:itemType>
        <xsl:value-of select="/ns1:Order/ns1:itemType"/>
      </ns1:itemType>
      <ns1:price>
        <xsl:value-of select="/ns1:Order/ns1:price"/>
      </ns1:price>
      <ns1:qty>
        <xsl:value-of select="/ns1:Order/ns1:qty"/>
      </ns1:qty>
      <ns1:status>
        <xsl:value-of select="/ns1:Order/ns1:status"/>
      </ns1:status>
      <ns1:creditCardInfo>
        <ns1:cardNumber>
          <xsl:value-of select="/ns1:Order/ns1:creditCardInfo/ns1:cardNumber"/>
        </ns1:cardNumber>
        <ns1:cardType>
          <xsl:value-of select="/ns1:Order/ns1:creditCardInfo/ns1:cardType"/>
        </ns1:cardType>
      </ns1:creditCardInfo>
    </ns1:Order>
  </xsl:template>
</xsl:stylesheet>
